return {
PlaceObj('ModItemBuildingTemplate', {
	'name', "AA70",
	'template_class', "ElectricityStorage",
	'pin_rollover_context', "electricity",
	'pin_rollover_hint', T{525471871733, --[[ModItemBuildingTemplate AA70 pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"},
	'pin_rollover_hint_xbox', T{526827620713, --[[ModItemBuildingTemplate AA70 pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"},
	'pin_progress_value', "current_storage",
	'pin_progress_max', "storage_capacity",
	'construction_cost_Concrete', 5000,
	'construction_cost_Polymers', 5000,
	'construction_entity', "AtomicBattery",
	'build_points', 2000,
	'dome_forbidden', true,
	'construction_state', "full",
	'maintenance_resource_type', "Polymers",
	'maintenance_resource_amount', 2000,
	'display_name', T{999274746328, --[[ModItemBuildingTemplate AA70 display_name]] "Atomic Accumulator "},
	'display_name_pl', T{633493813649, --[[ModItemBuildingTemplate AA70 display_name_pl]] "Atomic Accumulators"},
	'description', T{524699306470, --[[ModItemBuildingTemplate AA70 description]] "Stores Power at 70% efficiency. High capacity and max output, but charges slowly."},
	'build_category', "Power",
	'display_icon', "UI/Icons/Buildings/atomic_batteries.tga",
	'build_pos', 7,
	'entity', "AtomicBattery",
	'encyclopedia_image', "UI/Encyclopedia/AtomicAccumulator.tga",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'color_modifier', RGBA(236, 19, 207, 255),
	'palettes', "Outside_09",
	'demolish_sinking', range(15, 30),
	'demolish_tilt_angle', range(300, 600),
	'max_electricity_charge', 50000,
	'max_electricity_discharge', 100000,
	'conversion_efficiency', 70,
	'capacity', 2000000,
	'charge_animation', "charge",
	'empty_state', "idle",
	'full_state', "full",
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "FRConventional",
	'template_class', "FarmConventional",
	'resource_produced1', "Food",
	'max_storage1', 300000,
	'pin_rollover_hint', T{356258810119, --[[ModItemBuildingTemplate FRConventional pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"},
	'pin_rollover_hint_xbox', T{993617337843, --[[ModItemBuildingTemplate FRConventional pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"},
	'construction_cost_Concrete', 8000,
	'build_points', 2000,
	'is_tall', true,
	'dome_required', true,
	'upgrade1_id', "Farm_Automation",
	'upgrade1_display_name', T{732114167784, --[[ModItemBuildingTemplate FRConventional upgrade1_display_name]] "Automation"},
	'upgrade1_description', T{504188563278, --[[ModItemBuildingTemplate FRConventional upgrade1_description]] "Decreases Workplaces by <abs(upgrade1_add_value_1)>."},
	'upgrade1_icon', "UI/Icons/Upgrades/automation_01.tga",
	'upgrade1_upgrade_cost_Electronics', 5000,
	'upgrade1_mod_label_1', "Farm",
	'upgrade1_mod_prop_id_1', "max_workers",
	'upgrade1_add_value_1', -2,
	'upgrade3_id', "FoodRebalanceFarmUpgrade",
	'upgrade3_display_name', T{649123053521, --[[ModItemBuildingTemplate FRConventional upgrade3_display_name]] "Install Irrigation System"},
	'upgrade3_description', T{125444456483, --[[ModItemBuildingTemplate FRConventional upgrade3_description]] "Crops won't grow without Water. "},
	'upgrade3_upgrade_cost_Concrete', 3000,
	'upgrade3_upgrade_cost_Metals', 2000,
	'upgrade3_mod_label_1', "Farm",
	'upgrade3_mod_prop_id_1', "max_workers",
	'upgrade3_add_value_1', 6,
	'upgrade3_mod_label_2', "Farm",
	'upgrade3_mod_prop_id_2', "electricity_consumption",
	'upgrade3_add_value_2', 1,
	'upgrade3_mod_label_3', "Farm",
	'upgrade3_mod_prop_id_3', "performance",
	'upgrade3_add_value_3', -70,
	'display_name', T{809101111177, --[[ModItemBuildingTemplate FRConventional display_name]] "Farm"},
	'display_name_pl', T{369244900869, --[[ModItemBuildingTemplate FRConventional display_name_pl]] "Farms"},
	'description', T{687644501259, --[[ModItemBuildingTemplate FRConventional description]] "Produces Food. The Farm will only work when upgraded! "},
	'build_category', "Life-Support",
	'display_icon', "UI/Icons/Buildings/farm.tga",
	'build_pos', 9,
	'entity', "Farm",
	'encyclopedia_image', "UI/Encyclopedia/Farm.tga",
	'label1', "InsideBuildings",
	'color_modifier', RGBA(0, 248, 50, 255),
	'palettes', "Outside_06",
	'demolish_sinking', range(0, 0),
	'demolish_tilt_angle', range(300, 300),
	'electricity_consumption', 0,
	'active_shift', 1,
	'enabled_shift_2', false,
	'enabled_shift_3', false,
	'max_workers', 0,
	'specialist', "botanist",
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "FRFungal",
	'template_class', "FungalFarm",
	'resource_produced1', "Food",
	'max_storage1', 30000,
	'production_per_day1', 4000,
	'pin_rollover_hint', T{305840162650, --[[ModItemBuildingTemplate FRFungal pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"},
	'pin_rollover_hint_xbox', T{612233570462, --[[ModItemBuildingTemplate FRFungal pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"},
	'construction_cost_Concrete', 10000,
	'construction_cost_Metals', 15000,
	'construction_cost_Electronics', 5000,
	'build_points', 6000,
	'is_tall', true,
	'dome_forbidden', true,
	'upgrade1_id', "SuperfungusUpgrade",
	'upgrade1_display_name', T{669248276917, --[[ModItemBuildingTemplate FRFungal upgrade1_display_name]] "Superfungus"},
	'upgrade1_description', T{355319655359, --[[ModItemBuildingTemplate FRFungal upgrade1_description]] "+<upgrade1_mul_value_1>% Production; +<upgrade1_mul_value_2>% Oxygen Consumption."},
	'upgrade1_icon', "UI/Icons/Upgrades/superfungus_01.tga",
	'upgrade1_upgrade_cost_Polymers', 10000,
	'upgrade1_mod_label_1', "FungalFarm",
	'upgrade1_mod_prop_id_1', "production_per_day1",
	'upgrade1_mul_value_1', 50,
	'upgrade1_mod_label_2', "FungalFarm",
	'upgrade1_mod_prop_id_2', "air_consumption",
	'upgrade1_mul_value_2', 100,
	'upgrade2_id', "FungalFarm_Automation",
	'upgrade2_display_name', T{516443882916, --[[ModItemBuildingTemplate FRFungal upgrade2_display_name]] "Full Automation"},
	'upgrade2_description', T{970636687390, --[[ModItemBuildingTemplate FRFungal upgrade2_description]] "The Building will work at 100% efficiency without workers now. Requires 100% more Power. "},
	'upgrade2_icon', "UI/Icons/Upgrades/automation_01.tga",
	'upgrade2_upgrade_cost_Electronics', 10000,
	'upgrade2_upgrade_cost_MachineParts', 5000,
	'upgrade2_mod_label_1', "FungalFarm",
	'upgrade2_mod_prop_id_1', "max_workers",
	'upgrade2_add_value_1', -2,
	'upgrade2_mod_label_2', "FungalFarm",
	'upgrade2_mod_prop_id_2', "auto_performance",
	'upgrade2_add_value_2', 75,
	'upgrade2_mod_label_3', "FungalFarm",
	'upgrade2_mod_prop_id_3', "electricity_consumption",
	'upgrade2_mul_value_3', 100,
	'maintenance_resource_type', "Metals",
	'display_name', T{430759200960, --[[ModItemBuildingTemplate FRFungal display_name]] "Fungal Farm"},
	'display_name_pl', T{615495796122, --[[ModItemBuildingTemplate FRFungal display_name_pl]] "Fungal Farms"},
	'description', T{869515398807, --[[ModItemBuildingTemplate FRFungal description]] "A work-efficient outdoor Food production facility. Can work automated at 25% efficiency.  "},
	'build_category', "Life-Support",
	'display_icon', "UI/Icons/Buildings/fungal_farm.tga",
	'build_pos', 10,
	'entity', "FungalFarm",
	'encyclopedia_image', "UI/Encyclopedia/FungalFarm.tga",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'palettes', "FungalFarm",
	'demolish_sinking', range(10, 20),
	'demolish_tilt_angle', range(300, 600),
	'electricity_consumption', 10000,
	'water_consumption', 500,
	'air_consumption', 2000,
	'active_shift', 1,
	'enabled_shift_2', false,
	'enabled_shift_3', false,
	'max_workers', 2,
	'specialist', "botanist",
	'automation', 1,
	'auto_performance', 25,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "FRHydroponic",
	'template_class', "FarmHydroponic",
	'resource_produced1', "Food",
	'max_storage1', 100000,
	'pin_rollover_hint', T{743334406817, --[[ModItemBuildingTemplate FRHydroponic pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"},
	'pin_rollover_hint_xbox', T{653697559374, --[[ModItemBuildingTemplate FRHydroponic pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"},
	'construction_cost_Metals', 4000,
	'construction_cost_Polymers', 2000,
	'build_points', 2000,
	'is_tall', true,
	'dome_required', true,
	'upgrade1_id', "HydroponicFarm_Automation",
	'upgrade1_display_name', T{625601213393, --[[ModItemBuildingTemplate FRHydroponic upgrade1_display_name]] "Automation"},
	'upgrade1_description', T{714195184788, --[[ModItemBuildingTemplate FRHydroponic upgrade1_description]] "Decreases Workplaces by <abs(upgrade1_add_value_1)>."},
	'upgrade1_icon', "UI/Icons/Upgrades/automation_01.tga",
	'upgrade1_upgrade_cost_Electronics', 2000,
	'upgrade1_mod_label_1', "HydroponicFarm",
	'upgrade1_mod_prop_id_1', "max_workers",
	'upgrade1_add_value_1', -1,
	'upgrade2_id', "FoodRebalanceHydroponicsUpgrade",
	'upgrade2_display_name', T{130321993406, --[[ModItemBuildingTemplate FRHydroponic upgrade2_display_name]] "Install Irrigation and Heating"},
	'upgrade2_description', T{134787918241, --[[ModItemBuildingTemplate FRHydroponic upgrade2_description]] "Crops need significant care by trained Botanists to ensure optimal growing conditions."},
	'upgrade2_upgrade_cost_Metals', 1000,
	'upgrade2_upgrade_cost_Polymers', 1000,
	'upgrade2_mod_label_1', "HydroponicFarm",
	'upgrade2_mod_prop_id_1', "NonSpecialistPerformancePenalty",
	'upgrade2_mul_value_1', 200,
	'upgrade2_add_value_1', 90,
	'upgrade2_mod_label_2', "HydroponicFarm",
	'upgrade2_mod_prop_id_2', "max_workers",
	'upgrade2_add_value_2', 3,
	'upgrade2_mod_label_3', "HydroponicFarm",
	'upgrade2_mod_prop_id_3', "performance",
	'upgrade2_mul_value_3', 300,
	'maintenance_resource_type', "Metals",
	'display_name', T{977862311760, --[[ModItemBuildingTemplate FRHydroponic display_name]] "Hydroponic Farm"},
	'display_name_pl', T{424494764087, --[[ModItemBuildingTemplate FRHydroponic display_name_pl]] "Hydroponic Farms"},
	'description', T{760314781815, --[[ModItemBuildingTemplate FRHydroponic description]] "Crops need around the clock care by trained specialists. The Hydroponics will only work when upgraded!"},
	'build_category', "Life-Support",
	'display_icon', "UI/Icons/Buildings/hydroponics_farm.tga",
	'build_pos', 8,
	'entity', "HydroponicFarm",
	'encyclopedia_image', "UI/Encyclopedia/HydroponicFarm.tga",
	'label1', "InsideBuildings",
	'palettes', "Outside_06",
	'demolish_sinking', range(10, 25),
	'demolish_tilt_angle', range(300, 600),
	'electricity_consumption', 5000,
	'enabled_shift_2', false,
	'enabled_shift_3', false,
	'max_workers', 0,
	'specialist', "botanist",
	'hydroponic', true,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "PA70",
	'template_class', "ElectricityStorage",
	'pin_rollover_context', "electricity",
	'pin_rollover_hint', T{927640930547, --[[ModItemBuildingTemplate PA70 pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"},
	'pin_rollover_hint_xbox', T{345277370171, --[[ModItemBuildingTemplate PA70 pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"},
	'pin_progress_value', "current_storage",
	'pin_progress_max', "storage_capacity",
	'construction_cost_Concrete', 3000,
	'construction_cost_Polymers', 2000,
	'construction_entity', "FuelCell",
	'build_points', 1500,
	'dome_forbidden', true,
	'construction_state', "full",
	'maintenance_resource_type', "Polymers",
	'display_name', T{303705913100, --[[ModItemBuildingTemplate PA70 display_name]] "Power Accumulator"},
	'display_name_pl', T{670749756115, --[[ModItemBuildingTemplate PA70 display_name_pl]] "Power Accumulators"},
	'description', T{548498651217, --[[ModItemBuildingTemplate PA70 description]] "Stores Power at 70% efficiency. Amount of Power supplied is limited by the battery’s max output."},
	'build_category', "Power",
	'display_icon', "UI/Icons/Buildings/fuel_cell.tga",
	'build_pos', 6,
	'entity', "FuelCell",
	'encyclopedia_image', "UI/Encyclopedia/PowerAccumulator.tga",
	'build_shortcut1', "K",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'palettes', "Battery_WaterFuelCell",
	'demolish_sinking', range(5, 5),
	'demolish_tilt_angle', range(900, 1200),
	'demolish_debris', 85,
	'max_electricity_charge', 20000,
	'max_electricity_discharge', 20000,
	'conversion_efficiency', 70,
	'capacity', 200000,
	'charge_animation', "charge",
	'empty_state', "idle",
	'full_state', "full",
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "SolarPanelBigElectronics",
	'template_class', "SolarPanel",
	'pin_rollover_context', "electricity",
	'pin_rollover_hint', T{462131631326, --[[ModItemBuildingTemplate SolarPanelBigElectronics pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"},
	'pin_rollover_hint_xbox', T{744215479311, --[[ModItemBuildingTemplate SolarPanelBigElectronics pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"},
	'construction_cost_Metals', 4000,
	'build_points', 1500,
	'show_range_class', "ArtificialSun",
	'maintenance_resource_type', "Electronics",
	'maintenance_resource_amount', 200,
	'display_name', T{781546581438, --[[ModItemBuildingTemplate SolarPanelBigElectronics display_name]] "Large Solar Panel"},
	'display_name_pl', T{341053091191, --[[ModItemBuildingTemplate SolarPanelBigElectronics display_name_pl]] "Large Solar Panel"},
	'description', T{714965392769, --[[ModItemBuildingTemplate SolarPanelBigElectronics description]] "Generates Power during daytime. Its effectiveness is decreased by dust accumulation and during Dust Storms. Protected from dust while turned off."},
	'build_category', "Power",
	'display_icon', "UI/Icons/Buildings/solar_aray.tga",
	'build_pos', 2,
	'entity', "SolarPanelBig",
	'encyclopedia_image', "UI/Encyclopedia/LargeSolarPanel.tga",
	'build_shortcut1', "J",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'palettes', "SolarPanelBig",
	'demolish_sinking', range(5, 15),
	'demolish_tilt_angle', range(300, 600),
	'demolish_debris', 80,
	'electricity_production', 5000,
}),
PlaceObj('ModItemCode', {
	'name', "FoodRebalance",
	'FileName', "Code/FoodRebalance.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Fun with Constants",
	'FileName', "Code/Fun with Constants.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Lock Vanilla Power Buildings",
	'FileName', "Code/Lock Vanilla Power Buildings.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Mod Config",
	'FileName', "Code/Mod Config.lua",
}),
PlaceObj('ModItemCode', {
	'name', "No Outsourcing",
	'FileName', "Code/No Outsourcing.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Research and Breakthroughs",
	'FileName', "Code/Research and Breakthroughs.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Events",
	'FileName', "Code/Events.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Solar Panel Dust",
	'FileName', "Code/Solar Panel Dust.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Wind fluctuation",
	'FileName', "Code/Wind fluctuation.lua",
}),
}
