return PlaceObj('ModDef', {
	'title', "Realistic Mars (hard gameplay)",
	'description', "This Mod adds a whole bunch of new Gameplay and Difficulty Options. \r\n\r\nAbsolutely reqiures Mod Config by Waywocket:\r\nhttp://steamcommunity.com/sharedfiles/filedetails/?id=1340775972\r\n\r\nHave Fun.",
	'tags', "Gameplay, Realism, Hardcore, Research, Breakthroughs, Hard, Difficulty, Buildings, Other",
	'image', "Images/Hard Mode.png",
	'id', "LvDVa",
	'steam_id', "1339570684",
	'author', "Spannbeton",
	'version', 105,
	'lua_revision', 228184,
	'code', {
		"Code/Fun with Constants.lua",
		"Code/Lock Vanilla Power Buildings.lua",
		"Code/Mod Config.lua",
		"Code/No Outsourcing.lua",
		"Code/Research and Breakthroughs.lua",
		"Code/FoodRebalance.lua",
		"Code/Wind fluctuation.lua",
	},
	'saved', 1522581468,
})